config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.production?
    client_host = 'krankr.herokuapp.com'
    host = 'localhost'
  else
    client_host = 'localhost.euro'
    host = 'localhost'
  end


  root to: "admin/dashboard#index"

  scope '/:site_id' do

    get '/', to: 'client_side#index'

    get '/contact', to: 'client_side#contact', as: 'contact'
    get '/content/show/:content_id/:content_type', to: 'client_side#content_show', as: 'show_content'
    get '/service_types', to: 'client_side#service_types', as:'service_types_client'
    get '/actions', to: 'client_side#actions', as:'actions_client'
    get '/news', to: 'client_side#news', as:'news_client'
    get '/articles', to: 'client_side#articles', as:'articles_client'
    post '/orders', to: 'client_side#create_order'
    get '/orders/:order_id', to: 'client_side#order_show', as: 'order_show'
    get '/profiles/', to: 'client_side#profiles', as: 'profiles_client'
    get '/profiles/:profile_id', to: 'client_side#profiles_show', as: 'profiles_show_client'
    get '/comment/new', to: 'client_side#profiles_show', as: "comments"
    post '/comment/new', to: 'client_side#create_comment'
  # end


    scope '/admin' do
      root 'home#index', as: 'root_server'
      resources :client_cars
      resources :profiles
      resources :articles
      resources :news
      resources :service_types
      resources :orders
      get '/orders_by_status/(:year)/(:month)/(:day)', to: 'orders#index', as: 'orders_by_status'
      resources :clients
      # resources :settings
      get '/get_client_car/:client_id', to: 'clients#get_client_car'
      get '/settings', to: 'settings#index'
      get '/settings/:id/edit', to: 'settings#edit', as: 'edit_setting'
      patch  '/settings/:id(.:format)', to: 'settings#update', as: 'setting'
      resources :categories
      devise_for :workers
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client
  belongs_to :client_car
  belongs_to :profile
  has_many :order_service_types
  has_many :service_types, through: :order_service_types
  accepts_nested_attributes_for :order_service_types, allow_destroy: true
  enum status: [:in_progress, :finished, :need_check]

  default_scope {order('start_time')}

  # validates :name, presence: true

  validate :check_blank_time
  before_validation :set_end_time

  def set_end_time
    unless self.status == 'need_check'
      self.end_time = self.start_time + self.time_to_complete.seconds
    end
  end

  private

    def check_blank_time
      unless self.status == 'need_check'
        Order.all.each do |order|
          if order.start_time && order.end_time
            if (order.start_time..order.end_time).cover?(self.start_time) && order.profile_id == self.profile_id
              errors.add('!', "Работник занят с #{order.start_time.strftime("%d-%m-%y %H:%M")} по #{order.end_time.strftime("%d-%m-%y %H:%M")}")
            end
          end
        end
      end
    end
end

app/controllers/client_side_controller.rb
class ClientSideController < ApplicationController
  def index
    @news = News.where(is_action: false).limit(5)
    @actions = News.where(is_action: true).limit(5)
    @articles = Article.all.limit(5)
    render layout: 'application_client'
  end
  def actions
    @actions = News.where(is_action: true)
    render layout: 'application_client'
  end

  def contact
    render layout: 'application_client'
  end

  def articles
    @articles = Article.all
    render layout: 'application_client'
  end

  def news
    @news = News.where(is_action: false)
    render layout: 'application_client'
  end

  def service_types
    @data = {}
    ServiceType.all.each do |service_type|
      @data[service_type.category.title] ||= []
      @data[service_type.category.title] << service_type
    end
    @order = Order.new
    render layout: 'application_client'
  end

  def content_show
    if params[:content_type] == 'article'
      @object = Article.find(params[:content_id])
    elsif params[:content_type] == 'news' || params[:content_type] == 'action'
      @object = News.find(params[:content_id])
    end
    render layout: 'application_client'
  end

  def order_show
    @order = Order.find(params[:order_id])
    render layout: 'application_client'
  end

  def profiles
    @profiles = Profile.all
    render layout: 'application_client'
  end

  def profiles_show
    @profile = Profile.find(params[:profile_id])
    @comment = Comment.new
    render layout: 'application_client'
  end

  def create_order
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_show_path(@order.id), notice: 'Ваш заказ принят. Ожидайте звонка от менеджера :)' }
        format.json { render :show, status: :created, location: @order }
      else
        flash[:error] = @comment.errors.full_messages.to_sentence
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_comment
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to profiles_show_client_path(@comment.profile.id), notice: 'Спасибо. Комментарий успешно создан' }
      else
        flash[:error] = @comment.errors.full_messages.to_sentence
        format.html { redirect_to profiles_show_client_path(@comment.profile.id) }
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:profile_id, :author_name, :body)
  end
  def order_params
    params.require(:order).permit(:time_to_complete,:client_id, :detail_info, :status, :phone, :name, :email, :start_time, :total_amount, service_type_ids: [])
  end
end

app/helpers/client_side_helper.rb
module ClientSideHelper
end

app/views/client_side/_form.html.haml
= form_for @order, html: { class: "form-horizontal", role: "form" } do |f|
  -if @order.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :status, value: 'need_check'
  .row
    .col-xs-8
      .form-group
        .col-sm-2.control-label Услуги
        .col-sm-10
          = f.select :service_type_ids,  ServiceType.all.map{ |s| [s.title, s.id, 'data-amount' => "#{s.amount}", 'data-time' => "#{s.time_to_complete}"]}, {}, {multiple: true, class: 'form-control', size: 7}
      .form-group
        .col-sm-2.control-label Дополнительная информация
        .col-sm-10
          = f.text_field :detail_info, class: 'form-control'
    .col-xs-4
      .form-group
        .row
          .col-sm-2.control-label Время
          .col-sm-10
            .form-group
              #datetimepicker1.input-group.date
                = f.number_field :start_time, class: 'form-control', type: "text", value: Time.now
                %span.input-group-addon
                  %span.glyphicon.glyphicon-calendar
      .form-group
        %h3
          Ваш заказ:
        #total_amount
        = f.hidden_field :total_amount, class: 'form-control'
        = f.hidden_field :time_to_complete, class: 'form-control'
      .form-group
        = f.text_field :name, class: 'form-control', placeholder: 'Имя'
      .form-group
        = f.text_field :phone, class: 'form-control', placeholder: 'Телефон'
      .form-group
        = f.text_field :email, class: 'form-control', placeholder: 'Электронная почта'
      .form-group
        = f.submit 'Создать заказ', class: 'btn btn-primary'

app/views/client_side/_form_comment.html.haml
= form_for @comment, html: { class: "form-horizontal", role: "form" } do |f|
  -if @comment.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :profile_id, value: @profile.id
  .col-xs-12
    %hr
    .form-group
      = f.text_field :author_name, class: 'form-control', placeholder: "Введите ваше имя..."
    .form-group
      = f.text_field :body, class: 'form-control', placeholder: "Текст комментария..."
    .form-group.text-center
      = f.submit 'Оставить комментарий', class: 'btn btn-primary'

app/views/client_side/actions.html.haml
- provide(:title, 'Акции')
.container
  .row
    .col-xs-12
      - @actions.each do |action|
        .row
          .col-xs-12
            %h3
              = action.title
            = truncate_html(action.body, length: 300)
          .col-xs-12.small
            = link_to 'Читать дальше...', show_content_path(action.id, 'action')

app/views/client_side/articles.html.haml
- provide(:title, 'Статьи')
.container
  .row
    .col-xs-12
      - @articles.each do |article|
        .row
          .col-xs-12
            %h3
              = article.title
            = truncate_html(article.body, length: 300)
          .col-xs-12.small
            = link_to 'Читать дальше...', show_content_path(article.id, 'article')

app/views/client_side/contact.html.haml
.container
  .row
    .col-xs-12.text-center
      %h4 Контакты
      %hr
    .row
      .col-xs-4.col-xs-offset-4.well
        (044) 238-24-92
        %br/
        РАБОТАЕМ БЕЗ ВЫХОДНЫХ:
        %br/
        %i Пн-Пт: с 8:00 до 21:00
        %br/
        %i Сб-Вс: с 8:00 до 19:00

    .col-xs-6
      %h5 Адрес и телефон СТО Krankr
      ул. Киквидзе, 43 (Печерский район), Киев, Украина, 01103
      %br/
      тел. (044) 285-31-56 (документы, бухгалтерия)
    .col-xs-6
      %h5 E-mail
      order@krankr.com.ua - Вопросы по заказам
      %br/
      manager@krankr.com.ua - Реклама, Вакансии, Торговые предложения

app/views/client_side/content_show.html.haml
- provide(:title, @object.title)
.container
  .row
    .col-xs-12
      = link_to "< Назад", :back, class: 'btn'
      %h3
        = @object.title
      = @object.body.html_safe

app/views/client_side/index.html.haml
/ .jumbotron
/   %h1 Welcome!
/   %p ...
/   %p
/     %a.btn.btn-primary.btn-lg{:href => "#", :role => "button"} Learn more
/ .row
/   .col-xs-4
/     %h3.text-center Новости
/     - @news.each do |news|
/       = news
/     .small
/       = link_to 'Все новости', news_client_path
/   .col-xs-4
/     %h3.text-center Акции
/     - @actions.each do |action|
/       = action
/     .small
/       = link_to 'Все акции', actions_client_path
/   .col-xs-4
/     %h3.text-center Статьи
/     - @articles.each do |article|
/       = article
/     .small
/       = link_to 'Все Статьи', articles_client_path
%body#page-top
  %header
    .header-content
      .header-content-inner
        %h1{style: 'color: white'} Ваш любимый сервис всегда рядом!
        %hr/
        %a.btn.btn-primary.btn-xl.page-scroll{:href => "#about"} Узнать больше
  %section#services
    .container
      .row
        .col-lg-12.text-center
          %h2.section-heading Гарантируем
          %hr.primary/
    .container
      .row
        .col-lg-3.col-md-6.text-center
          .service-box
            %i.fa.fa-4x.fa-car.wow.bounceIn.text-primary
            %h3 Подход
            %p.text-muted Вы можете смело рассчитывать на результат
        .col-lg-3.col-md-6.text-center
          .service-box
            %i.fa.fa-4x.fa-clock-o.wow.bounceIn.text-primary{"data-wow-delay" => ".1s"}
            %h3 Сроки
            %p.text-muted Вы экономите своё время!
        .col-lg-3.col-md-6.text-center
          .service-box
            %i.fa.fa-4x.fa-money.wow.bounceIn.text-primary{"data-wow-delay" => ".2s"}
            %h3 Стоимость
            %p.text-muted Вы сохраняете свои деньги
        .col-lg-3.col-md-6.text-center
          .service-box
            %i.fa.fa-4x.fa-thumbs-o-up.wow.bounceIn.text-primary{"data-wow-delay" => ".3s"}
            %h3 Качество
            %p.text-muted Вы пользуетесь лучшим
  %section#about.bg-primary{style: 'padding-top: 50px!important;'}
    .container
      .row.text-center.news
        .col-xs-4
          %h3.text-center
            = link_to 'Новости', news_client_path
          - @news.each do |news|
            %br/
            = link_to news.title, show_content_path(news.id, 'news')
        .col-xs-4
          %h3.text-center
            = link_to 'Акции', actions_client_path
          - @actions.each do |action|
            %br/
            = link_to action.title, show_content_path(action.id, 'action')
        .col-xs-4
          %h3.text-center
            = link_to 'Статьи', articles_client_path
          - @articles.each do |article|
            %br/
            = link_to article.title, show_content_path(article.id, 'article')
  %aside.bg-dark
    .container.text-center
      .call-to-action
        %h2 Лучшие условия только у нас!
        %a.btn.btn-default.btn-xl.wow.tada{:href => "#"} Запишись на обслуживание!
  %section#contact
    .container
      .row
        .col-lg-8.col-lg-offset-2.text-center
          %h2.section-heading Let's Get In Touch!
          %hr.primary/
          %p Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!
        .col-lg-4.col-lg-offset-2.text-center
          %i.fa.fa-phone.fa-3x.wow.bounceIn
          %p +38099-377-22-77
        .col-lg-4.text-center
          %i.fa.fa-envelope-o.fa-3x.wow.bounceIn{"data-wow-delay" => ".1s"}
          %p
            %a{:href => "mailto:your-email@your-domain.com"} krankr@feedback.com

app/views/client_side/news.html.haml
- provide(:title, 'Новости')
.container
  .row
    .col-xs-12
      - @news.each do |news|
        .row
          .col-xs-12
            %h3
              = news.title
            = truncate_html(news.body, length: 300)
          .col-xs-12.small
            = link_to 'Читать дальше...', show_content_path(news.id, 'news')

app/views/client_side/order_show.html.haml
- provide(:title, "Спасибо! Заказ №#{@order.id}")
.container
  .row
    .col-xs-12.text-center
      %h4 Спасибо за заказ!
      %hr
      %h5
        ="Номер заказа №#{@order.id}"
      %h4 
        Услуги которые вы выбрали:
        = @order.service_types.map{ |service_type| service_type.title}.join(',')
      %h4 
        Сумма к оплате:
        = "#{@order.total_amount}грн."
      %h4
        Время на выполнение заказа:
        = Time.at(@order.time_to_complete).utc.strftime("%Hч %Mхв")

app/views/client_side/profiles.html.haml
- provide(:title, 'Работники')
.container
  .row
    %hr
    .col-xs-12
      - @profiles.each do |profile|
        .col-xs-12.col-sm-6.col-md-6
          .well.well-sm
            .row
              .col-sm-6.col-md-4
                =image_tag profile.photo_url.big, class: "img-rounded img-responsive"
              .col-sm-6.col-md-8
                %h4
                  = link_to "#{profile.last_name} #{profile.first_name}", profiles_show_client_path(profile.id)
                %small
                  %i
                    Выполнено заказов:
                    %span{style: 'font-size: 16px;'}
                      = profile.orders.count
                %p
                  = profile.description
                %p
                  = succeed profile.date_of_birthday do
                    %i.glyphicon.glyphicon-gift

app/views/client_side/profiles_show.html.haml
.container
  = link_to "< Назад", :back, class: 'btn'
  .row
    .col-md-6.col-xs-offset-3
      .well.well-sm
        .row
          .col-sm-6.col-md-4
            =image_tag @profile.photo_url.big, class: "img-rounded img-responsive"
          .col-sm-6.col-md-8
            %h4
              = "#{@profile.last_name} #{@profile.first_name} #{@profile.third_name}"
            %h5
              %i
                = @profile.description
            %h5
              %i
                Выполнено заказов:
                = @profile.orders.count
            %p
              = succeed "  #{@profile.date_of_birthday}" do
                %i.glyphicon.glyphicon-gift
  %i.text-center
    %h4
      Комментарии:
  %hr
  .row
    .col-md-8.col-xs-offset-2
      - @profile.comments.each do |comment|
        .media
          .media-left.media-middle
            %a{:href => "#"}
              = image_tag 'default_avatar.png'
          .media-body
            %h4.media-heading
              = comment.author_name
            .small
              = comment.created_at.strftime("%d-%m-%y")
            = comment.body
      = render partial: 'client_side/form_comment'

app/views/client_side/service_types.html.haml
- provide(:title, 'Услуги')
.container
  .row
    .col-xs-12
      %h3
        Наши услуги:
      - @data.each do |category_name, service_types|
        .row
          .col-xs-12
            %h4
              = category_name
            - service_types.each do |service_type|
              .col-xs-4.well{style: 'border: 1px solid #e5e5e5'}
                .row
                  .col-xs-12
                    = service_type.title
                  .col-xs-12.text-right
                    = "Цена #{service_type.amount} грн."
        %hr
    .col-xs-12
      %h3
        Сделайте заказ
    = render partial: 'client_side/form'