config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.production?
    client_host = 'krankr.herokuapp.com'
    host = 'localhost'
  else
    client_host = 'localhost.euro'
    host = 'localhost'
  end


  root to: "admin/dashboard#index"

  scope '/:site_id' do

    get '/', to: 'client_side#index'

    get '/contact', to: 'client_side#contact', as: 'contact'
    get '/content/show/:content_id/:content_type', to: 'client_side#content_show', as: 'show_content'
    get '/service_types', to: 'client_side#service_types', as:'service_types_client'
    get '/actions', to: 'client_side#actions', as:'actions_client'
    get '/news', to: 'client_side#news', as:'news_client'
    get '/articles', to: 'client_side#articles', as:'articles_client'
    post '/orders', to: 'client_side#create_order'
    get '/orders/:order_id', to: 'client_side#order_show', as: 'order_show'
    get '/profiles/', to: 'client_side#profiles', as: 'profiles_client'
    get '/profiles/:profile_id', to: 'client_side#profiles_show', as: 'profiles_show_client'
    get '/comment/new', to: 'client_side#profiles_show', as: "comments"
    post '/comment/new', to: 'client_side#create_comment'
  # end


    scope '/admin' do
      root 'home#index', as: 'root_server'
      resources :client_cars
      resources :profiles
      resources :articles
      resources :news
      resources :service_types
      resources :orders
      get '/orders_by_status/(:year)/(:month)/(:day)', to: 'orders#index', as: 'orders_by_status'
      resources :clients
      # resources :settings
      get '/get_client_car/:client_id', to: 'clients#get_client_car'
      get '/settings', to: 'settings#index'
      get '/settings/:id/edit', to: 'settings#edit', as: 'edit_setting'
      patch  '/settings/:id(.:format)', to: 'settings#update', as: 'setting'
      resources :categories
      devise_for :workers
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :body, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :service_types
  validates :title, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :orders
  has_many :client_cars
end

app/models/client_car.rb
class ClientCar < ActiveRecord::Base
  belongs_to :client
  validates :model, presence: true
  validates :license_plate, presence: true

  has_many :orders, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :profile

  validates :author_name, presence: true
  validates :body, presence: true
end

app/models/news.rb
class News < ActiveRecord::Base
  validates :title, :body, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client
  belongs_to :client_car
  belongs_to :profile
  has_many :order_service_types
  has_many :service_types, through: :order_service_types
  accepts_nested_attributes_for :order_service_types, allow_destroy: true
  enum status: [:in_progress, :finished, :need_check]

  default_scope {order('start_time')}

  # validates :name, presence: true

  validate :check_blank_time
  before_validation :set_end_time

  def set_end_time
    unless self.status == 'need_check'
      self.end_time = self.start_time + self.time_to_complete.seconds
    end
  end

  private

    def check_blank_time
      unless self.status == 'need_check'
        Order.all.each do |order|
          if order.start_time && order.end_time
            if (order.start_time..order.end_time).cover?(self.start_time) && order.profile_id == self.profile_id
              errors.add('!', "Работник занят с #{order.start_time.strftime("%d-%m-%y %H:%M")} по #{order.end_time.strftime("%d-%m-%y %H:%M")}")
            end
          end
        end
      end
    end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :worker
  validates_associated :worker

  has_many :comments

  mount_uploader :photo_url, AvatarUploader

  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :third_name, presence: true
  validates :date_of_birthday, presence: true
  validates :photo_url, presence: true
  validates :description, presence: true

  # validates_attachment :photo, content_type: { content_type: /\Aimage\/.*\Z/ },
  #                               size: { in: 0..1.megabytes }
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  has_many :order_service_types
  has_many :orders, through: :order_service_types
  # has_many :client_bid_service_types
  # has_many :client_bid, through: :client_bid_service_types
  belongs_to :category

  validates :title, presence: true
  validates :category, presence: true
  validates :amount, presence: true
  validates :time_to_complete, presence: true
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  attr_accessor :login
  validate :validate_username

  has_one :profile, dependent: :destroy
  has_many :comments
  before_create :build_default_profile
  before_create :add_role_for_worker

  def validate_username
    if Worker.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def add_role_for_worker
    # self.add_role "admin"
  end

  def build_default_profile
    build_profile
    true
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/shared/_client_header.html.haml
/ %nav.navbar.navbar-default.navbar-fixed-top
/   .container
/     .navbar-header
/       %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
/         %span.sr-only Toggle navigation
/         %span.icon-bar
/         %span.icon-bar
/         %span.icon-bar
/       = link_to "Krankr", root_path, class: "navbar-brand"
/     #navbar.collapse.navbar-collapse
/       %ul.nav.navbar-nav
/         %li{class: current_page?(service_types_client_path) ? 'active' : ''}
/           = link_to 'Услуги', service_types_client_path
/         %li{class: current_page?(actions_client_path) ? 'active' : ''}
/           = link_to 'Акции', actions_client_path
/         %li{class: current_page?(news_client_path) ? 'active' : ''}
/           = link_to 'Новости', news_client_path
/         %li{class: current_page?(articles_client_path) ? 'active' : ''}
/           = link_to 'Статьи', articles_client_path
/         %li{class: current_page?(profiles_client_path) ? 'active' : ''}
/           = link_to 'Работники', profiles_client_path
%nav#mainNav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to @site.title, root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{class: current_page?(service_types_client_path) ? 'active' : ''}
          = link_to 'Услуги', service_types_client_path
        %li{class: current_page?(profiles_client_path) ? 'active' : ''}
          = link_to 'Работники', profiles_client_path
        %li{class: current_page?(actions_client_path) ? 'active' : ''}
          = link_to 'Акции', actions_client_path
        %li{class: current_page?(news_client_path) ? 'active' : ''}
          = link_to 'Новости', news_client_path
        %li{class: current_page?(articles_client_path) ? 'active' : ''}
          = link_to 'Статьи', articles_client_path
        %li{class: current_page?(contact_path) ? 'active' : ''}
          = link_to 'Контакты', contact_path

app/views/shared/_flash.html.haml
- flash.each do |type, message|
  %div{:class => "alert #{bootstrap_class_for(type)} fade in"}
    = message

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Krankr", root_path, class: "navbar-brand"
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: current_page?(clients_path) ? 'active' : ''}
          = link_to 'Клиенты', clients_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Заказы
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'Создать заказ', new_order_path
            %li.divider
            %li
              = link_to 'Требуют проверки', orders_by_status_path(type: 'need_check')
            %li
              = link_to 'В процессе', orders_by_status_path(type: 'in_progress')
            %li
              = link_to 'Выполненые', orders_by_status_path(type: 'finished')
        %li{class: current_page?(service_types_path) ? 'active' : ''}
          = link_to 'Типы услуг', service_types_path
        %li{class: current_page?(categories_path) ? 'active' : ''}
          = link_to 'Категории', categories_path
        %li{class: current_page?(profiles_path) ? 'active' : ''}
          = link_to 'Работники', profiles_path
        %li{class: current_page?(settings_path) ? 'active' : ''}
          = link_to 'Настройки', settings_path
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Медиа
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'Новости', news_index_path
            %li
              = link_to 'Статьи', articles_path
      %ul.nav.navbar-nav.navbar-right
        - if worker_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_worker.email
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to 'Сменить пароль', edit_worker_registration_path
              %li
                = link_to 'Выйти', destroy_worker_session_path, {method: :delete}
        - else
          %li
            = link_to 'Войти', new_worker_session_path
          %li
            = link_to 'Регистрация', new_worker_registration_path