config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.production?
    client_host = 'krankr.herokuapp.com'
    host = 'localhost'
  else
    client_host = 'localhost.euro'
    host = 'localhost'
  end


  root to: "admin/dashboard#index"

  scope '/:site_id' do

    get '/', to: 'client_side#index'

    get '/contact', to: 'client_side#contact', as: 'contact'
    get '/content/show/:content_id/:content_type', to: 'client_side#content_show', as: 'show_content'
    get '/service_types', to: 'client_side#service_types', as:'service_types_client'
    get '/actions', to: 'client_side#actions', as:'actions_client'
    get '/news', to: 'client_side#news', as:'news_client'
    get '/articles', to: 'client_side#articles', as:'articles_client'
    post '/orders', to: 'client_side#create_order'
    get '/orders/:order_id', to: 'client_side#order_show', as: 'order_show'
    get '/profiles/', to: 'client_side#profiles', as: 'profiles_client'
    get '/profiles/:profile_id', to: 'client_side#profiles_show', as: 'profiles_show_client'
    get '/comment/new', to: 'client_side#profiles_show', as: "comments"
    post '/comment/new', to: 'client_side#create_comment'
  # end


    scope '/admin' do
      root 'home#index', as: 'root_server'
      resources :client_cars
      resources :profiles
      resources :articles
      resources :news
      resources :service_types
      resources :orders
      get '/orders_by_status/(:year)/(:month)/(:day)', to: 'orders#index', as: 'orders_by_status'
      resources :clients
      # resources :settings
      get '/get_client_car/:client_id', to: 'clients#get_client_car'
      get '/settings', to: 'settings#index'
      get '/settings/:id/edit', to: 'settings#edit', as: 'edit_setting'
      patch  '/settings/:id(.:format)', to: 'settings#update', as: 'setting'
      resources :categories
      devise_for :workers
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :orders
  has_many :client_cars
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_worker!

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.page(params[:page]).per(10)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client_car = ClientCar.new
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_client_car
    render json: {cars: Client.find(params[:client_id]).client_cars}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :phone)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for @client, html: { class: "form-horizontal", role: "form" } do |f|
  -if @client.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"

      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :phone, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :phone, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/clients/edit.html.haml
.page-header
  = link_to clients_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Назад
  = link_to @client, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Открыть
  %h1 Изменить Клиента

= render 'form'

app/views/clients/index.html.haml
.page-header
  = link_to new_client_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    Создать Клиента
  %h1 Список Клиентов

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Имя
        %th Почта
        %th Телефон
        %th
        %th
        %th

    %tbody
      - @clients.each do |client|
        %tr
          %td= client.name
          %td= client.email
          %td= client.phone
          %td= link_to 'Открыть', client
          %td= link_to 'Редактировать', edit_client_path(client)
          %td= link_to 'Удалить', client, data: { confirm: 'Вы уверены?' }, method: :delete
  = paginate @clients

app/views/clients/new.html.haml
.page-header
  = link_to clients_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New client

= render 'form'

app/views/clients/show.html.haml
.page-header
  = link_to clients_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Назад
  .row
    .col-xs-6
      %h3 Страница Клиента
    .col-xs-6.text-right
      = link_to 'Редактировать', edit_client_path(@client), class: 'btn btn-primary'
%dl.dl-horizontal
  %dt Имя:
  %dd= @client.name
  %dt Почта:
  %dd= @client.email
  %dt Телефон:
  %dd= @client.phone

.row
  .col-xs-6
    %h4 Автомобили:
  .col-xs-6.text-right
    = link_to "Добавить автомобиль", '#', :onclick => "showClientCarForm(this)", class: 'btn btn-success', id: 'show_form_button'
  .col-xs-12
    %hr
.row
  - @client.client_cars.each do |car|
    .col-sm-6.col-md-4
      .thumbnail
        / %img{:alt => "...", :src => "..."}/
        .caption
          = link_to car.brand, car
          %p
            = link_to 'Редактировать', edit_client_car_path(car), class: 'btn btn-primary'
            = link_to 'Удалить', car, data: { confirm: 'Вы уверены?' }, method: :delete, class: 'btn btn-danger'

= form_for @client_car, html: { class: "form-horizontal", role: "form", style: 'display: none;' } do |f|
  -if @client_car.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@client_car.errors.count, "error")} prohibited this client_car from being saved:"

      %ul
        - @client_car.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :client_id, value: @client.id, class: 'form-control'
  .form-group
    = f.label :brand, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :brand, class: 'form-control'
  .form-group
    = f.label :model, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :model, class: 'form-control'
  .form-group
    = f.label :license_plate, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :license_plate, class: 'form-control'
  .form-group
    = f.label :vin, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :vin, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Создать автомобиль', class: 'btn btn-primary'
    = link_to "Скрыть форму", '#', :onclick => "hideClientCarForm()", class: 'btn btn-success'